name: Publish gitmsg package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js 20.x (GitHub npm registry)
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          registry-url: https://npm.pkg.github.com/
          scope: "@alismx"
      - name: Install dependencies
        run: pnpm install --prod
      - name: Generate client
        run: pnpm run build
      - name: Publish package
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}